### ISSUE TITLE
Minimum Spanning tree **Prim** in Python 

### ISSUE THREAD

**Issue by Aniket762** [Aniket762/Project-alpha#118]

**Comment by AnjaliBhuva** [comment]
I would like to contribute to this, can you plz assign it to me?

**Comment by edoardottt** [comment]
[Here you can find Python, C, C#, C++, Java](https://www.geeksforgeeks.org/prims-minimum-spanning-tree-mst-greedy-algo-5/)

**Comment by Aditya489** [comment]
Hi can you assign this to me?
