### ISSUE TITLE
Breadth First Search (BFS) in Java 

### ISSUE THREAD

**Issue by Aniket762** [Aniket762/Project-alpha#12]

**Comment by motabhai-bhagwaan** [comment]
Hi, can you please assign me this issue? 
Thank you.

**Comment by bvamc** [comment]
Hi @Aniket762 , can I work on this? or DFS?

**Comment by Aniket762** [comment]
Hey @motabhai-bhagwaan  go for it 💪

**Comment by Aniket762** [comment]
Hey @bvamc it will be great if you can create a PR for DFS

Happy Coding 😀
