### ISSUE TITLE
Minimum Coin problem in python

### ISSUE THREAD

**Issue by ary1733** [Aniket762/Project-alpha#131]
write a function in Python which takes input c = [c1,c2, .... cn] different denomination of coin and target value. and return minum coins needed to fulfil the request.
def coinExchange(C,M) #return minimum coins required

example test case C= [1 , 4, 9] and M= 12 ,ans = 3 which is 3 coins of value 4

**Comment by SravanthiKaki** [comment]
Can I work on this?

**Comment by ary1733** [comment]
Sure

**Comment by Aniket762** [comment]
Thanks @ary1733 for generating the issue
