### ISSUE TITLE
largest element in array in C++

### ISSUE THREAD

**Issue by SayantanMaiti** [Aniket762/Project-alpha#141]

**Comment by dash-anurag** [comment]
Can i work on this?

**Comment by SayantanMaiti** [comment]
@dash-anurag Sure!

**Comment by dash-anurag** [comment]
Hello, I am having issues with two files CPP/Factorial.cpp and CPP/factorial.cpp colliding with each other and I cannot delete one of in my Forked repo. Can you help me with it.

**Comment by Sindhu-321** [comment]
Can I get this task assigned? Thanks.

**Comment by harshitalashkari** [comment]
can i work on this ?

**Comment by bhavya092** [comment]
Can you assign this task to me ? I will work in C++

**Comment by bhavinisehgal18** [comment]
Can you assign me this task ? I can work on c++

**Comment by aryanmanchanda** [comment]
can you assign me with this task?
