### ISSUE TITLE
roots of quadratic equation in C++

### ISSUE THREAD

**Issue by SayantanMaiti** [Aniket762/Project-alpha#172]

**Comment by aalok28** [comment]
Can  I go for it?

**Comment by SayantanMaiti** [comment]
@aalok28 Sure! Go for it!

**Comment by PardeepKumar816** [comment]
can u assign it to me i can do this i java and c++

**Comment by aalok28** [comment]
Hey @SayantanMaiti can u please assign this again as I have removed myself by mistake from this assignment?

**Comment by SayantanMaiti** [comment]
@pardeep596 Let me know if you are interested to do the same in Java. I'll create an issue for you :)

**Comment by PardeepKumar816** [comment]
> @pardeep596 Let me know if you are interested to do the same in Java. I'll create an issue for you :)

Yes I am interested to do this in Java

**Comment by SayantanMaiti** [comment]
@pardeep596 Good to know! I've added the issue, comment on it so that I can assign it to you.
