### ISSUE TITLE
factorial of number using recursion in C++

### ISSUE THREAD

**Issue by SayantanMaiti** [Aniket762/Project-alpha#176]

**Comment by parwinakhtari** [comment]
I can do this.

**Comment by PardeepKumar816** [comment]
please assign it to me i can do this in java and c++

**Comment by mohinesh9999** [comment]
please assign it to me i can do it in c++,java,python and javascript

**Comment by Andy9822** [comment]
I can give it a try since the 2 dudes haven't said anything else
