### ISSUE TITLE
Check Leap Year Java

### ISSUE THREAD

**Issue by Aniket762** [Aniket762/Project-alpha#29]

**Comment by riyabhatia26** [comment]
Can I work on this one?

**Comment by PODU** [comment]
I would Like to work on this.

**Comment by Aniket762** [comment]
Hey @PODU this is already assigned sorry

**Comment by harshitalashkari** [comment]
Assign this to me please.thank you

**Comment by riyabhatia26** [comment]
Thanks for assigning this to me. I have added code in the java folder and created a pull request. Please let me know if I am missing something.
