### ISSUE TITLE
Shortest Path from source to all vertices **Dijkstra** in C++

### ISSUE THREAD

**Issue by Aniket762** [Aniket762/Project-alpha#39]

**Comment by Dkgiri619** [comment]
Assign it to me

**Comment by Dkgiri619** [comment]
I have started to work on it.

**Comment by Dkgiri619** [comment]
wait i did something wrong with PR.

**Comment by Dkgiri619** [comment]
I will correct it and send you the PR

**Comment by Dkgiri619** [comment]
@Aniket762 i have sent the PR. Don't mind the previous mention, by mistake sent the PR to my own forked repo. Thanks.
