### ISSUE TITLE
Find factorial in C

### ISSUE THREAD

**Issue by SayantanMaiti** [Aniket762/Project-alpha#52]

**Comment by PODU** [comment]
I would like to work on this.

**Comment by SaloniK17** [comment]
Hey! , can you please assign me this issue?
Thank you.

**Comment by SAKSHI2569** [comment]
I want to work on it , will you please assign me this issue?
Thanks.

**Comment by rishika-singh49** [comment]
I would like to work on this.....
will you please assign me this issue?

**Comment by PriyanshTri** [comment]
can you assign this to me. Thankyou
