### ISSUE TITLE
Simple calculator in C++

### ISSUE THREAD

**Issue by SayantanMaiti** [Aniket762/Project-alpha#53]
Basic operations of addition, subtraction, multiplication, division.
You may include other operations if you want.

**Comment by mhechavarria** [comment]
i would like to work on this, please assign me

**Comment by Itachi8374** [comment]
please assign it to me, i would be happy to contribute

**Comment by rishika-singh49** [comment]
i am interested in this....will you please assign me this issue

**Comment by NandiniMundra-8** [comment]
I would like to work on this ,please could you assign me @mhechavarria ?
can I perform it using c or java language ?

**Comment by bhavesh-jo** [comment]
please assign

**Comment by mhechavarria** [comment]
PR submited! Thanks!
