### ISSUE TITLE
Edit Distance in Java

### ISSUE THREAD

**Issue by sumana2001** [Aniket762/Project-alpha#72]
Given two strings str1 and str2 and below operations that can performed on str1. Find minimum number of edits (operations) required to convert ‘str1’ into ‘str2’.
1. Insert
2. Remove
3. Replace
All of the above operations are of equal cost.

**Comment by AnkitaM84** [comment]
Hey I would like to work on this!
Thank you

**Comment by sumana2001** [comment]
Sure! Go ahead😄

**Comment by minks21** [comment]
Can you please assign this to me ?

**Comment by AnkitaM84** [comment]
I have unassigned myself because I won't be able to complete this task for a few days. So I felt someone else can make use of this opportunity :)

**Comment by Nilesh-Ghone** [comment]
Hi @sumana2001 - Can you please kindly assign this to me, I would like work on this? Thank you.

**Comment by Nilesh-Ghone** [comment]
> Hi @sumana2001 - Can you please kindly assign this to me, I would like work on this? Thank you.

Gentle Reminder - can you pls kindly assign this to me?

**Comment by Nilesh-Ghone** [comment]
Thank you @Aniket762 - I will start on this and create PR for your review and acceptance.

**Comment by Nilesh-Ghone** [comment]
Hi @Aniket762 and @sumana2001 - I have created "Pull Request" for this issue resolution, Please kindly review, suggest your comments if any and merge. Thank you.
