### ISSUE TITLE
Minimum Partition in C

### ISSUE THREAD

**Issue by sumana2001** [Aniket762/Project-alpha#74]
Given a set of integers, the task is to divide it into two sets S1 and S2 such that the absolute difference between their sums is minimum.
If there is a set S with n elements, then if we assume Subset1 has m elements, Subset2 must have n-m elements and the value of abs(sum(Subset1) – sum(Subset2)) should be minimum.

**Comment by StephenTrainor** [comment]
Mind if I take a shot at this?
