### ISSUE TITLE
Minimum Partition in C++

### ISSUE THREAD

**Issue by sumana2001** [Aniket762/Project-alpha#75]
Given a set of integers, the task is to divide it into two sets S1 and S2 such that the absolute difference between their sums is minimum.
If there is a set S with n elements, then if we assume Subset1 has m elements, Subset2 must have n-m elements and the value of abs(sum(Subset1) – sum(Subset2)) should be minimum.

**Comment by Ansh8236** [comment]
Hey @sumana2001 ! 
I am new to Github and contributing to open source projects. So don't know much about the way it all goes but would love to explore it beginning from here. I would like to work on this problem. Kindly assign this to me.

**Comment by sumana2001** [comment]
Yes definitely! Happy coding!
