### ISSUE TITLE
Minimum Partition in Java

### ISSUE THREAD

**Issue by sumana2001** [Aniket762/Project-alpha#77]
Given a set of integers, the task is to divide it into two sets S1 and S2 such that the absolute difference between their sums is minimum.
If there is a set S with n elements, then if we assume Subset1 has m elements, Subset2 must have n-m elements and the value of abs(sum(Subset1) – sum(Subset2)) should be minimum.

**Comment by filipkule** [comment]
I will do this

**Comment by sumana2001** [comment]
Sure! Go ahead😄

**Comment by Ashutoshnegi880** [comment]
please assign me this
