### ISSUE TITLE
Transpose of matrix in CPP

### ISSUE THREAD

**Issue by SayantanMaiti** [Aniket762/Project-alpha#86]

**Comment by Itachi8374** [comment]
Please assign this issue to me @SayantanMaiti

**Comment by SayantanMaiti** [comment]
@Itachi8374 Sure. Go for it!

**Comment by adhamale2810** [comment]
please assign it to me
@SayantanMaiti

**Comment by adhamale2810** [comment]
@SayantanMaiti please reply, if you are assigning it to me or letting the other guy deal with this issue.
