### ISSUE TITLE
Transpose of matrix in Java

### ISSUE THREAD

**Issue by SayantanMaiti** [Aniket762/Project-alpha#87]

**Comment by CYPHER0041** [comment]
I'll do this

**Comment by PriyanshTri** [comment]
Can I do this in python? thanks...

**Comment by NandiniMundra-8** [comment]
hey @Aniket762 , I would love to take this task up ?

**Comment by CYPHER0041** [comment]
@SayantanMaiti  I created the PR but I didn't link it to this issue and therefore it is still open. Can something be done to resolve this?
