### ISSUE TITLE
Matrix multiplication in CPP

### ISSUE THREAD

**Issue by SayantanMaiti** [Aniket762/Project-alpha#95]

**Comment by appsx13** [comment]
Can i work on this?

**Comment by sumana2001** [comment]
Sure! Go ahead😄

**Comment by priyalgupta09** [comment]
hey! can you please assign this repository to me.

**Comment by PriyanshTri** [comment]
can I work on this?

**Comment by bhavesh-jo** [comment]
i have a program just for this can I work

**Comment by Paola351** [comment]
@SayantanMaiti i would like to code that in Java :D
